### ISSUE TITLE
Find readily available or at least publishable large sample image

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#10]
The larger sample data I've been using `Xenium_FFPE_Human_Breast_Cancer_Rep1_if_image.tif` was obtained from 10X genomics, but isn't super-duper easy to fetch especially not programmatically.

It would be nice if we had a comparable ~500MB sample available.

**Comment by lynnlangit** [comment]
Would love to test with a range of public images submitted by the bioinformatics community.

If your work includes cellular image segmentation, we'd welcome links to public data that relates to your work area.

**Comment by lynnlangit** [comment]
Can we use these input data samples? https://deepcell.readthedocs.io/en/latest/data-gallery/index.html
