### ISSUE TITLE
Submit bug report to skimage for offset case

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#146]
While working on #128 I found some discrepancies between my implementation and scikit's that I couldn't explain, when using a non-null offset. (aka recentering the footprint)

After a lot of head-banging, I actually think I found a bug in the scikit implementation.

Work:
- [ ] create a document showing the bug & why it's not the expected result
- [ ] submit to skimage: https://github.com/scikit-image/scikit-image/issues

**Comment by lynnlangit** [comment]
nicely documented

use the simplest thing that works

**Comment by dchaley** [comment]
Bug report submitted: https://github.com/scikit-image/scikit-image/issues/7315
