### ISSUE TITLE
Tile large image into even larger image

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#157]
Take this image:
gs://davids-genomics-data-public/cellular-segmentation/hubmap/hbm873.pcpz.247.904M-px/input_channels.npz

and tile it into 2x2, with the 3 new tiles rotated by 90, 180, and 270 degrees.

Or, do whatever is most appropriate to retile that image into a big image.

Resulting size: 3.6M pixels

**Comment by WeihaoGe1009** [comment]
i have created the image that contains 4 tiles, rotating by 0, 90, 180, and 270 degrees. But i don't have the permission to upload the final npz file. can we have a separate bucket that gives me permission to upload?

**Comment by dchaley** [comment]
Gave Weihao permissions to upload to the bucket; here is the file uploaded:
gs://davids-genomics-data-public/cellular-segmentation/hubmap/hbm873.pcpz.247.904M-px/quad-tiled-2670M-px.npz

Resulting size: 2,670 M pixels (2.7B)

Currently testing in notebook b/c it's too big to view on local computers.

**Comment by dchaley** [comment]
We verified that the image looks like 4 rotated tiles. Currently running through benchmark on highmem-96– closing this ticket!
