### ISSUE TITLE
Change array name in 2.7B image

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#158]
Currently the array name in this npz:
gs://davids-genomics-data-public/cellular-segmentation/hubmap/hbm873.pcpz.247.904M-px/quad-tiled-2670M-px.npz

is `final_image`, for consistency it should be `input_channels`.

If we want to run more benchmarks on this, it'll make our lives much easier.

**Comment by lynnlangit** [comment]
Is this done @WeihaoGe1009 ?
