### ISSUE TITLE
Run benchmark on Google Batch

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#183]
Run a benchmark on Google Batch. Need to adjust the code to fetch the machine type.

☐ benchmark with CPU
❌ benchmark with GPU   (after >24hrs)

**Comment by dchaley** [comment]
Jobs with GPU have not even started, ~24+ hours later 😨

**Comment by lynnlangit** [comment]
tips - use `n2-standard-x` instances, also try another region `us-central1`(?)

**Comment by dchaley** [comment]
Running `STANDARD` provisioning, n1-standard-8 machine, w/ T4 GPU:
STATUS_CHANGED	2024-04-30T21:16:14.809370937Z	
Job state is set from SCHEDULED to RUNNING for job projects/148281182590/locations/us-central1/jobs/j20240430-gpu-standard-1.
STATUS_CHANGED	2024-04-30T21:08:44.860491667Z	
Job state is set from QUEUED to SCHEDULED for job projects/148281182590/locations/us-central1/jobs/j20240430-gpu-standard-1.

**Comment by lynnlangit** [comment]
did the run complete ok?  How long did it take?  Using 1 image of what size?

**Comment by dchaley** [comment]
512x512, completed in 38s of runtime. Creation --> completion was ~8min. Successfully wrote to BigQuery too 🎉    cc @WeihaoGe1009 

This means we can work on running an arbitrary file in the container, and handle output. (Right now, the python script hardcodes its input & params. In the notebook we'd just change it inline.)

**Comment by dchaley** [comment]
Closing this issue as we've completed benchmarks on cpu + gpu!
