### ISSUE TITLE
Find way to shrink container

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#192]
The current container is 8.5 GB which takes a looooong time to download.

It most likely does not need to be this big, it's (apparently) a lot of GPU drivers.
We only need the GPU drivers that we'll use.

Can we remove the other drivers?    ---> there are probably lots of best practices to look up

**Comment by dchaley** [comment]
Base image for TF 2.8: but does it have python? (and if we install python + TF, does it reinstall TF?)
https://hub.docker.com/layers/tensorflow/tensorflow/2.8.4-gpu/images/sha256-4351b59baf4887bcf47eb78b34267786f40460a81fef03c9b9f58e7d58f1c7b7?context=explore

**Comment by lynnlangit** [comment]
Ideas:

- Use smaller base image
- Use Docker laying / caching
- Install GPU drivers for T4 GPU only (remove others)

**Comment by dchaley** [comment]
Attempt: [image streaming[(https://cloud.google.com/batch/docs/use-image-streaming): **FAIL**   😿 

Yesterday's results [[logs](https://console.cloud.google.com/logs/query;query=logName%3D%22projects%2Fdeepcell-on-batch%2Flogs%2Fbatch_task_logs%22%20OR%20%22projects%2Fdeepcell-on-batch%2Flogs%2Fbatch_agent_logs%22%20labels.job_uid%3D%22j20240430-gpu-stan-a1b352d8-5c4f-4bbb0%22%20timestamp%3E%3D%222024-04-30T20:54:59.284Z%22%20timestamp%3C%3D%222024-04-30T23:03:01.287Z%22%20severity%3E%3DDEFAULT;cursorTimestamp=2024-04-30T22:02:35.722220681Z?project=deepcell-on-batch)]:

From batch starts initializing until we start our container: 
```
2024-04-30 14:56:20.150 PDT Cloud Batch server: "batch.googleapis.com:443"
2024-04-30 15:02:23.233 PDT Executing runnable container
```
Almost exactly 6 minutes to load the container (& the GPU driver install).


Attempt 1: failed due to insufficient disk (??)   [[logs](https://cloudlogging.app.goo.gl/fxcdGbps6UrxQeLo6)]

```
failed to pull and unpack image "us-central1-docker.pkg.dev/deepcell-on-batch/deepcell-benchmarking-us-central1/benchmarking:gce": failed to extract layer sha256:5bfd133cf20faa9b20611c91cc59c104a1295d6ae3ef0cfd6aa3ea573df21780: write /var/lib/containerd/io.containerd.snapshotter.v1.gcfs/snapshotter/snapshots/36/fs/opt/conda/lib/python3.7/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-37m-x86_64-linux-gnu.so: no space left on device: unknown
```

Note failed to extract; no space left (on unknown device).

Attempt 2: failed due to ... not sure? Couldn't find the file. [[batch job](https://console.cloud.google.com/batch/jobsDetail/regions/us-central1/jobs/j20240501-nogpu-spot-2/logs?project=deepcell-on-batch)]

```
2024-05-01 13:29:42.012 PDT
python: can't open file 'benchmarking/deepcell-e2e/benchmark.py': [Errno 2] No such file or directory
```

**Comment by lynnlangit** [comment]
<img width="1138" alt="Screenshot 2024-05-01 at 8 29 26 PM" src="https://github.com/dchaley/deepcell-imaging/assets/1609620/3ff53960-cf97-4cac-8038-8c74677848ba">
Is it the first one listed?

**Comment by lynnlangit** [comment]
might want to test streaming with a smaller container and w/out need to install gpu drivers to see if streaming works at all

**Comment by dchaley** [comment]
Good idea– I created #204 to follow up on streaming (while we pursue actually shrinking the container here)

**Comment by lynnlangit** [comment]
After today's work - would you consider this complete? Size is now < 2.5 GB right?

**Comment by dchaley** [comment]
Complete enough for now probably, although I think we can remove a few
caches. (A possible followup)

**Comment by dchaley** [comment]
Reopening; the code isn't actually committed yet

**Comment by dchaley** [comment]
Follow-up optimization opportunity: #209
