### ISSUE TITLE
Set up GCP Batch results table

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#201]
As we add more test variables (e.g. spot vs standard) we need to take note of those properties in benchmark results.

Add a column for this.

**Comment by dchaley** [comment]
Maybe, we should just add a new table for batch results. Wdyt @lynnlangit ?

**Comment by lynnlangit** [comment]
> Maybe, we should just add a new table for batch results. Wdyt @lynnlangit ?

yes please do

**Comment by dchaley** [comment]
Created table:
deepcell-401920.benchmarking.results_batch

Removed columns: kernel, gcp_service, is_first_run
Added column: provisioning_model

**Comment by dchaley** [comment]
Fun fact: we ran into a "time travel" feature/bug: https://stackoverflow.com/questions/68984952/bigquery-drop-table-column-ddl-bug/69291989#69291989
