### ISSUE TITLE
Some logs in Batch show up as errors but aren't

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#220]
Some of the logs show up as errors even though they're labeled info or debug. This is disconcerting 😅   figure out why...

![Image](https://github.com/dchaley/deepcell-imaging/assets/352005/67814ffd-42f9-4f2b-87b5-80886729cdd4)

**Comment by lynnlangit** [comment]
yes, we have seen this in other envs too - would be interested to hear what the Batch team says about this...

**Comment by dchaley** [comment]
From Shamel: 

Use this library: https://pypi.org/project/JSON-log-formatter/

Then do something like this:

```
import logging
from json_log_formatter import JSONFormatter

class GCPFormatter(JSONFormatter):
    def json_record(self, message: str, extra: dict, record: logging.LogRecord) -> dict:
        extra['severity'] = record.levelname
        return super(GCPFormatter, self).json_record(message, extra, record)

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
handler = logging.StreamHandler()
formatter = GCPFormatter()
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.info("Log message", extra={'custom_field_1': "foo", 'custom_field_2': "bar"})
```
