### ISSUE TITLE
Investigate rebuilding TF2.8 container

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#226]
The image we built starting from tf 2.8 has a number of vulnerabilities:

![Image](https://github.com/dchaley/deepcell-imaging/assets/352005/7bb03689-b1e7-4642-a1ea-8341d84263ad)

The container was built 2 years ago. DeepCell depends on tf 2.8.

Can we rebuild this container using most recent base linux etc, but with TF 2.8?

**Comment by dchaley** [comment]
[Build log with vulnerabilities](https://console.cloud.google.com/artifacts/docker/deepcell-on-batch/us-central1/deepcell-benchmarking-us-central1/benchmarking/sha256:8f67407450c054861113165ccbf680f974ed2d0a7cef7ddb1b70f43060fa8ba3;tab=vulnerabilities?pageState=(%22ar-vulnerabilities%22:(%22f%22:%22%255B%257B_22k_22_3A_22Effective%2520Severity_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22High_5C_22_22%257D_2C%257B_22k_22_3A_22Fix%2520Available_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22No_5C_22_22%257D%255D%22))&project=deepcell-on-batch)

**Comment by lynnlangit** [comment]
Of note is that the released version of DeepCell requires TF 2.8 (current version of TF is 2.16)

**Comment by dchaley** [comment]
I rebuilt the TensorFlow 2.8.4 container on Ubuntu 22.04 (from 20.04): [tensorflow-2.8.4-redux](https://github.com/dchaley/tensorflow-2.8.4-redux)

I rebuilt the DeepCell container using this new container, and published to the `gce` tag which the run-job.py script uses.

Method: [Rebuilding TensorFlow 2.8.4 on Ubuntu 22.04 to patch vulnerabilities](https://dev.to/dchaley/rebuilding-tensorflow-284-on-ubuntu-2204-to-patch-vulnerabilities-3j3m)

Results: 

![Image](https://github.com/dchaley/deepcell-imaging/assets/352005/573edbb7-d912-448f-9b31-8d36a7816326)
