### ISSUE TITLE
Verify Batch network interface in allocation policy

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#246]
Our target environment VMs don't have public IP addresses.

That means we need to do some extra steps, as outlined here: https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#NetworkInterface

In particular `noExternalIpAddress` needs to be `true`, and we need to specify the network/subnet.

We can't test it remotely. We could test a similar setup by creating a comparable network/subnet, but we won't do that unless it doesn't "Just Work" in the target environment.

**Comment by dchaley** [comment]
This was confirmed to work in target environment with a network/subnet, no need to test further ourselves.

**Comment by lynnlangit** [comment]
great to see this and thanks. FYI 'target env' also requires the "service account" parameter in the JSON file.  I have tested the SA perm with a 'from a bucket-to NF-to a bucket' sample job and it worked ok.
