### ISSUE TITLE
Incorporate h_maxima improvements into DeepCell

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#28]
Apply results from this effort: https://github.com/dchaley/deepcell-imaging/issues/8

into `deepcell-toolbox`, specifically the [deep_watershed implementation](https://github.com/vanvalenlab/deepcell-toolbox/blob/3698762c346ce2ec829745a86c219ae304e7f3a3/deepcell_toolbox/deep_watershed.py#L179)

1: implement into scikit, release, update scikit in DeepCell
2: release fast-hybrid separately, integrate into DeepCell

**Comment by lynnlangit** [comment]
what is the status?  is the PR being accepted a 'done' indicator for this task?

**Comment by dchaley** [comment]
No, this issue is unstarted. It depends on completing either #1 or #2 above.

**Comment by dchaley** [comment]
Removing this from the workstream as it's not really related– performance yes, benchmark project no.

**Comment by dchaley** [comment]
Mesmer [postprocessing function](https://github.com/vanvalenlab/deepcell-tf/blob/master/deepcell/applications/mesmer.py#L100).

calls [deep_watershed](https://github.com/vanvalenlab/deepcell-toolbox/blob/master/deepcell_toolbox/deep_watershed.py#L45) in deepcell_toolbox.

calls [scikit.h_maxima](https://github.com/scikit-image/scikit-image/blob/146b55cc0c58733882fd03ef021f8b12fa175d22/skimage/morphology/extrema.py#L48)

calls [scikit.reconstruct](https://github.com/scikit-image/scikit-image/blob/146b55cc0c58733882fd03ef021f8b12fa175d22/skimage/morphology/grayreconstruct.py#L8)

This `reconstruct` function is what we need to replace with our [implementation of fast_hybrid_reconstruct](https://github.com/dchaley/deepcell-imaging/blob/main/benchmarking/h_maxima/benchmark_utils.py#L281).

**Possible approach?** Fork the repositories then specify requirements.txt pointing to those forks (which have optimizations)

**Comment by dchaley** [comment]
Converted to a milestone: [Release grayreconstruct optimizations to scikit-image
](https://github.com/dchaley/deepcell-imaging/milestone/1)
