### ISSUE TITLE
Build setup/instructions for cython fast-hybrid

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#29]
The [cython fast-hybrid](https://github.com/dchaley/deepcell-imaging/pull/27) implementation is a bit "raw", requiring manual `cythonify` in the right directory etc.

The file should be repackaged into a proper module in `deepcell-imaging`, with appropriate `setup.py` etc. so that pip knows to build the extension as part of installation.

This could also be accomplished by publishing the fast-hybrid implementation as its own library, and including that as a dependency to this repo.

**Comment by lynnlangit** [comment]
what is the next step here?
