### ISSUE TITLE
Determine what happened to previous mesmer samples

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#33]
The mesmer samples [we extracted](https://github.com/dchaley/deepcell-imaging/blob/9b8cbdd4f194c09d79a839221a2e6eda10aa2415/notebooks/Extract-Sample-Channels.ipynb) used a [previous commit's dataset](https://github.com/vanvalenlab/deepcell-tf/blob/9e5fe9ab6237b7529dd6603038e002121fea291a/deepcell/datasets/__init__.py) no longer available in the [deepcell-tf main branch](https://github.com/vanvalenlab/deepcell-tf).

From commit history it looks like the dataset may have been replaced with the [tissue_net dataset](https://github.com/vanvalenlab/deepcell-tf/blob/259f35f574290a728cae966cb6f812cdccc2ab38/deepcell/datasets/tissue_net.py). The expected hash values don't match, but this could be just the naming inside the .npz file.

Objective of this work: determine the difference between the old commit data (which is still available on s3 as of 2023-11-17 at least) and the newly available tissue net data.

**Comment by lynnlangit** [comment]
status?  did you include the updated data in this repo? (so download from s3 is no longer needed)

**Comment by dchaley** [comment]
This is unstarted as we haven't looked at the updated data yet. The previously downloaded data are in the links referenced above (as well as in cloud storage, referenced from the notebook).

**Comment by lynnlangit** [comment]
do we need this anymore? can we close this?

**Comment by dchaley** [comment]
Let's close it out. We may revisit the tissue_net samples for retraining (etc) – but for now we've moved on!
