### ISSUE TITLE
Test notebook with 4 GPUs

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#6]

**Comment by lynnlangit** [comment]
Test on Lynn's GCP project - get project info from Lynn

**Comment by lynnlangit** [comment]
Did test (reported results in sheet) w/2 and 4 NIVDIA T4 GPUs.  Oddly better perf w/2 GPUs of this type (than 4).
Other GPUs to test  **V100** (2x cost of T4s) and possibly **TPU v2 Pod** (512 cores) 16GB RAM (costs 1.5x T4 GPU)

**Comment by lynnlangit** [comment]
Suspect that we need to verify the CUDA drivers and configuration on the runtime used - WIP to test...

**Comment by lynnlangit** [comment]
Don't think we'll need 4 GPUs - testing with 1 or 2 GPUs max - so closing this one
