### ISSUE TITLE
Create runnable 'predict' notebook

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#7]
As a user I can: go to github repo, download it to local, get ipython notebook, get sample data, upload notebook to test env, (vertex ai), config info (instance types/size, GPUs, ...) to verify. (Part of test is to figure out config parameters)

- [ ] Notebook that runs prediction on parameterized input file
- [ ] Script to create notebook execution w/ specified machine parameters (instance type, GPU)

Result of running notebook: timing matrix of input size vs config parameters

Benchmark will be: whole-cell compartment. (Potentially add nuclear/both later, opportunity for parallelization later.)

**Comment by lynnlangit** [comment]
This notebook will be designed to test the impact of 1-to-n GPUs of various available types on the `predict` section of DeepCell if I understand correctly.

**Comment by dchaley** [comment]
Need to parameterize a notebook. AKA, "run this notebook" for "these parameters".

AFAICT Vertex AI supports papermill style parameters:
https://github.com/nteract/papermill

See also: https://cloud.google.com/vertex-ai/docs/workbench/managed/executor-parameters

Basically we tag a notebook cell with `parameters` then, when we run through the executor, we add the parameter key/value pairs.

**Comment by dchaley** [comment]
Declaring the notebook part done. Some followup: https://github.com/dchaley/deepcell-imaging/issues/43, https://github.com/dchaley/deepcell-imaging/issues/44, https://github.com/dchaley/deepcell-imaging/issues/45
