### ISSUE TITLE
Get cost tables

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-imaging#87]
Fill out the cost tables in [this sheet](https://docs.google.com/spreadsheets/d/1mHeKZqoH0-XrrV_P0uTwXNrwQCkcM6lbTZKGmMYKb8k/edit#gid=398126074).

![Image](https://github.com/dchaley/deepcell-imaging/assets/352005/a5935fb5-aba2-4977-a9c4-6671a6215543)

Method:
- Start creating a notebook.
- Select hardware configuration.
- You should see a cost table like this:

![Image](https://github.com/dchaley/deepcell-imaging/assets/352005/57b0c059-efd7-4a2d-9581-16ec54fcbec5)

- Copy these fields into the sheet: 
  - TOTAL (put this into discounted $/mo)
  - Sustained use discount (put this into discount $/mo)
- Then copy the other computed columns from previous rows

**Comment by dchaley** [comment]
We got a bunch of these & we'll just add more as we find them. See sheet tab: https://docs.google.com/spreadsheets/d/1mHeKZqoH0-XrrV_P0uTwXNrwQCkcM6lbTZKGmMYKb8k/edit#gid=398126074

**Comment by lynnlangit** [comment]
great to see this - I think I'd like to test a2 instances as well (included GPUs optimized for a2's) - not trying to be too random, but always wanted to test a2s, seems like a good use case...

**Comment by dchaley** [comment]
Looks like I can't use A2's 😞 

<img width="775" alt="Screenshot 2023-12-11 at 5 00 48 PM" src="https://github.com/dchaley/deepcell-imaging/assets/352005/c1228d93-8ac6-4f9c-993e-64e8165363a6">

How about you @lynnlangit ?


I'm also quota'd to 24 CPUs meaning I'm stuck at 16 and the next lowest is 32. Quota increase to 96 is pending…

Interestingly, managed notebooks only proposes n1 machines. But check out my user-managed options:

<img width="533" alt="Screenshot 2023-12-11 at 5 02 16 PM" src="https://github.com/dchaley/deepcell-imaging/assets/352005/508d0f29-5508-4dab-b4b9-9cb02230c7b0">

The new "Instances" type gives me a middle-of-the-road selection:

<img width="533" alt="Screenshot 2023-12-11 at 5 03 00 PM" src="https://github.com/dchaley/deepcell-imaging/assets/352005/d2cc232f-e5a5-4e18-b79d-be874907098a">

🤔

**Comment by lynnlangit** [comment]
I can use A2s :)
